version: '3'
services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.48.1
    networks:
      - localnetwork
    shm_size: 1gb
    ipc: host
    cap_add:
      - SYS_ADMIN
    environment:
      - SHOPWARE_BASE_URL
      - PAYPAL_USERNAME
      - PAYPAL_PASSWORD
    volumes:
      - ../scripts/e2e.sh:/e2e.sh
      - ../tmp/:/tmp/
      - ../../../test-report:/tmp/test-report

networks:
  localnetwork:
    external: true
