name: Build Adyen Plugin on Release

on:
  release:
    types:
      - published

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shopware_version: [6.6.0, latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Plugin for Shopware ${{ matrix.shopware_version }}
        run: |
          # Pokretanje Dockware sa odgovarajućom verzijom
          docker run --rm -v ${{ github.workspace }}:/var/www/html/custom/plugins \
            -e SHOPWARE_VERSION=${{ matrix.shopware_version }} \
            dockware/dev:${{ matrix.shopware_version }} \
            bash -c "
              # Instalacija zavisnosti
              composer install --no-dev --optimize-autoloader

              # Build plugina
              cd /var/www/html/custom/plugins/adyen-shopware6
              ./bin/build.sh
            "

      - name: Push Docker Image for Shopware ${{ matrix.shopware_version }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/adyen-shopware6:${{ matrix.shopware_version }}
