name: Build Adyen Plugin on Release

on:
  release:
    types:
      - published

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shopware_version: [6.4.0.0, latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image for Shopware ${{ matrix.shopware_version }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/adyen-shopware6:${{ matrix.shopware_version }}
          build-args: |
            SHOPWARE_TAG=${{ matrix.shopware_version }}
